//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaloryLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseModel : DbContext
    {
        public DatabaseModel()
            : base("name=DatabaseModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__migrationhistory> C__migrationhistory { get; set; }
        public virtual DbSet<diaryentries> diaryentries { get; set; }
        public virtual DbSet<ingrediententries> ingrediententries { get; set; }
        public virtual DbSet<ingredients> ingredients { get; set; }
        public virtual DbSet<loginingredientrelations> loginingredientrelations { get; set; }
        public virtual DbSet<logins> logins { get; set; }
        public virtual DbSet<recipeentries> recipeentries { get; set; }
        public virtual DbSet<recipeingredientrelations> recipeingredientrelations { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
    }
}
