//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaloryLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class calorycalculatorEntities : DbContext
    {
        public calorycalculatorEntities()
            : base("name=calorycalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__migrationhistory> C__migrationhistory { get; set; }
        public virtual DbSet<ingredients> ingredients { get; set; }
        public virtual DbSet<loginingredientrelations> loginingredientrelations { get; set; }
        public virtual DbSet<logins> logins { get; set; }
        public virtual DbSet<recipeingredientrelations> recipeingredientrelations { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
    }
}
