//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaloryLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingrediententries
    {
        public int IngredientEntryId { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public Nullable<int> DiaryEntry_DiaryEntryId { get; set; }
        public Nullable<int> Ingredient_IngredientId { get; set; }
    
        public virtual diaryentries diaryentries { get; set; }
        public virtual ingredients ingredients { get; set; }
    }
}
