//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaloryLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginingredientrelations
    {
        public int LoginIngredientRelationId { get; set; }
        public Nullable<int> Ingredient_IngredientId { get; set; }
        public Nullable<int> Login_LoginId { get; set; }
    
        public virtual ingredients ingredients { get; set; }
        public virtual logins logins { get; set; }
    }
}
