//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaloryLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginingredientrelations
    {
        public int LoginIngredientRelationId { get; set; }
        public Nullable<int> Ingredient_IngredientId { get; set; }
        public Nullable<int> Login_LoginId { get; set; }
    
        public virtual ingredients ingredients { get; set; }
        public virtual logins logins { get; set; }
    }
}
